export default [
  "The [[Frontend Engineer]] Your [[Backend]] Warned You About",
  "[[Specialist]] in Moving [[Pixels]] Exactly 3px to the Left",
  "I Break [[CSS]] So The [[Users]] Don’t Have To",
  "Known to Add [[One Class]] and [[Fix Everything]]",
  "World-Class [['Why Is This 1px Off?']] Investigator",
  "I Make [[Skeleton Loaders]] Look [[Faster]] Than Reality",
  "Turning Requirements Into [[It Looks Better Now]]",
  "Senior [[Have You Tried Flex?]] Consultant",
  "The [[Frontend Engineer]] Who Reads [[Design Mocks]]",
  "I [[Optimize]] 12ms and [[Celebrate]]",
  "I Can Stop Using [[Tailwind]] Anytime, I Just [[Don't]]",
  "Accessible, Performant, [[Mildly Addictive Interfaces]]",
  "I [[Refactor]] Components Until They Confess",
  "I Reduce [[Figma]] To Reality",
  "I Fix Layouts Caused By [[One More Feature]]",
  "[[Dark Mode]] Therapist",
  "I Can [[Center]] Things, Even In 2025",
  "The [[Frontend Engineer]] Who Deletes [[Code]] For Sport",
  "90% Removing CSS, [[10% Coffee]]",
  "I Add [[Animations]] Where Feelings Should Be",
  "I Rename [[Final_v4_copy(2)]] To [[Done]]",
  "Single Source of Truth, [[Multiple Opinions]]",
  "I Make [[Spinners]] Spin Less",
  "[[Pixels]] Fear Me, [[Designers]] Love Me",
  "I Translate [[Make It Pop]] To [[CSS]]",
  "I Push to [[Prod]] Before Lunch [[(Sometimes)]]",
  "I Make Your [[Lighthouse Scores]] Swipe Right",
  "I Build [[UI]] That Survives [[Real Users]]",
  "The [[Frontend Engineer]] You'll Blame Less",
  "I Hard [[Refresh]] For A Living",
  "I Make [[Edge Cases]] Feel Included",
  "I Write [[CSS]] So Readable It Explains Itself",
  "I [[Animate]] Without Making Your [[Laptop]] Cry",
  "I Turn [['We'll Fix It Later]] Into Today",
  "I [[Debug]] With A Sixth Sense For [[z-index]]",
  "I Ship [[UIs]] That Don't Need A Tour",
  "I Make [[Modals]] Behave Like Guests",
  "I Make The [[Save Button]] Worth [[Clicking]]",
  "I Turn [[TODOs]] Into [[TADAs]]",
  "I Make [[Design Systems]] Pay Rent",
  "I [[Delete]] 200 Lines, Add [[One Variable]]",
  "I Build With [[Empathy]], Ship With [[Swagger]]",
  "I Make [[Loading]] Feel Like [[Anticipation]]",
  "I Keep Your Brand From Kerning Off A [[Cliff]]",
  "Your [[Pixel]] Pusher",
  "The [[Frontend Engineer]] That Your Company Pretends It Doesn't Need",
  "Crafting [[Wow]] For Your Company, One [[Div]] At A Time",
  "The Frontend Engineer Who Will Actually Read [[Design Tokens]]",
  "The [[Frontend Engineer]] Your Company Didn't Know It [[Needed]]",
  "I Make Your Company's [[UI]] Look Like It Went To [[Therapy]]",
  "[[Debugging]] Your Company's Layouts Since [[Right Now]]",
  "Making Your Company's Website [[2% Faster,]] [[98% Sexier]]",
  "Turning Your Company's [[Design Mocks]] Into [[Reality]] (Mostly)",
  "[[Pixel-Perfect]] For Your Company, Unless You Zoom To 400%",
  "I Put The [[Fun]] In Your Company's [[Frontend]]",
  "Making Your Company's Customers Forget The [[Backend]] Exists",
  "I Turn Your Company's [[Coffee Budget]] Into [[CSS]]",
  "Fixing Your Company's [[UI]] One Misaligned [[Button]] At A Time",
  "The [[Frontend Engineer]] Your Company Will Claim As [[Culture Fit]]",
  "I Make Your Company's [[Loading Screens]] Look Intentional",
  "From [[TODO]] To [[TADA]]: Shipping [[UI]] For Your Company",
  "Saving Your Company From Another [[Bootstrap]] Clone",
  "The [[Frontend Engineer]] Bold Enough For Your Company's [[Design Team]]",
  "I'll Make Your Company's [[Modal]] Actually Close On [[Click]]",
  "Responsible For Your Company's Next [[Design Award]]",
  "I Add Delight To Your Company's [[Dark Mode]]",
  "Making Your Company Look Better In Every [[Browser]] (Even IE11… maybe)",
  "I [[Animate]] Your Company's [[UI]] Without Dropping Frames",
  "Because Your Company Deserves A [[Frontend]] That [[Pops]]",
  "I Write The [[CSS]] That Makes Your Company Look [[Effortless]]",
  "Turning Your Company's [[Brand Guidelines]] Into Real [[Pixels]]",
  "I Make Your Company's [[Dashboard]] Less Sad",
  "Upgrading Your Company's [[Frontend]] From [[Meh]] To [[Wow]]",
  "Helping Your Company [[Ship Features]] Without [[Shipping Bugs]]",
  "Keeping Your Company's [[UX]] From [[Rage Tweets]]",
  "The [[Frontend Engineer]] That Will Finally [[Fix]] Your Company's Navbar",
  "I Give Your Company A [[UX]] Glow-Up",
  "Making Your Company's [[Components]] Play [[Nice]] Together",
  "I Turn Your Company's [[Design System]] Into A [[Real System]]",
  "The [[Frontend Engineer]] Who Will Help Your [[Company]] Steal [[Customers]]",
  "I Make Your Company's [[UI]] Feel As Good As It Looks",
  "Turning Your Company's [[Brand Colors]] Into Pure [[Vibes]]",
  "Helping Your Company Impress [[Users]] Faster Than [[Competitors]]",
  "The [[Frontend Engineer]] Who Actually Tests Your Company's [[UI]]",
  "Because Your Company's [[Customers]] Deserve [[Nice Things]]",
  "I Turn Your Company's [[Redesign]] Into Reality [[(Without Tears)]]",
  "Making Your Company's [[UI]] So Smooth, You'll Forget The [[Backend]]",
  "I [[Optimize]] Your Company's [[DOM]] For Fun And Profit",
  "Building [[UI]] That Makes Your Company's [[Marketing]] Look Honest",
  "I Keep Your Company's [[CEO]] From Saying [[Why Is This Slow?]]",
  "Fixing Your Company's [[Frontend]] So The [[Backend]] Can Relax",
  "Making Your Company's [[Web App]] Feel Native, Without The [[App Store]]",
  "I Turn Your Company's [[Roadmap]] Into Something [[Shippable]]",
];
