import Head from 'next/head';
import About from '../components/About';

// Components
import Container from '../components/Container';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="bg-primary relative min-h-screen bg-primary-light font-jakarta dark:bg-primary-dark">
      <Head>
        {/* Replace this with next-seo */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <main className="mt-20 min-h-screen">
          <header className="my-40">
            <h1 className="text-6xl text-heading-lg leading-tight text-primary-dark dark:text-primary-light">
              <span className="text-js-yellow">Front-End Engineer</span> of Your
              Dreams
            </h1>

            <About />
          </header>
        </main>

        <Footer />
      </Container>
    </div>
  );
}
